import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Lazy initializer for Gemini API client
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is missing.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// System prompt instructing the AI Assistant
const SYSTEM_INSTRUCTION = `You are Sumit Tuition App's AI Assistant, an expert educational administrator and data analyst for a tuition center / coaching academy.
Your task is to analyze student, class, attendance, fee, test, homework, and syllabus structured JSON data and generate clear, professional, actionable, and encouraging reports in clean Markdown format.

RULES:
1. Format output cleanly in beautiful, well-structured Markdown with appropriate headings (##, ###), bullet points, bold highlights, and tables where helpful.
2. Provide specific, data-backed insights based on the provided JSON data.
3. Keep tone professional, empathetic, constructive, and action-oriented.
4. Highlight risks clearly (e.g. attendance < 75%, unpaid fees, declining test marks) and offer practical remediation strategies.
5. NEVER suggest or imply automatic modification of database records. All suggestions are for human review.
6. When writing parent communications, use polite, clear, and professional language with appropriate placeholders if needed.`;

// API Route: AI Report Generation
app.post("/api/ai/report", async (req, res) => {
  try {
    const { reportType, dataPayload, promptExtra } = req.body;

    if (!dataPayload) {
      return res.status(400).json({ error: "Missing dataPayload in request body" });
    }

    const ai = getGeminiClient();

    let userPrompt = `Analysis Request Type: ${reportType}\n\n`;
    userPrompt += `Provided Institution / Student Structured JSON Data:\n\`\`\`json\n${JSON.stringify(dataPayload, null, 2)}\n\`\`\`\n\n`;

    if (promptExtra) {
      userPrompt += `Additional Instructions / Focus Area:\n${promptExtra}\n\n`;
    }

    userPrompt += `Please generate the requested ${reportType} report in clean, well-formatted Markdown following the system guidance.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: userPrompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0.4,
      },
    });

    const markdownText = response.text || "No response generated by AI.";

    return res.json({
      success: true,
      markdown: markdownText,
      timestamp: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error("Error generating AI report:", err);
    return res.status(500).json({
      error: err.message || "Failed to generate AI report. Please verify your API key and network connection.",
    });
  }
});

// API Route: Ask AI Chat Endpoint
app.post("/api/ai/chat", async (req, res) => {
  try {
    const { query, dataContext, history } = req.body;

    if (!query) {
      return res.status(400).json({ error: "Missing query in request body" });
    }

    const ai = getGeminiClient();

    let fullPrompt = `Context Data on Sumit Tuition App Institution & Students:\n\`\`\`json\n${JSON.stringify(dataContext || {}, null, 2)}\n\`\`\`\n\n`;

    if (history && Array.isArray(history) && history.length > 0) {
      fullPrompt += `Previous Conversation History:\n`;
      history.forEach((item: { role: string; text: string }) => {
        fullPrompt += `${item.role === "user" ? "Admin" : "AI Assistant"}: ${item.text}\n`;
      });
      fullPrompt += `\n`;
    }

    fullPrompt += `Admin Question: ${query}\n\n`;
    fullPrompt += `Provide a helpful, precise, and well-formatted Markdown answer based directly on the provided context data.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: fullPrompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0.3,
      },
    });

    return res.json({
      success: true,
      reply: response.text || "I could not analyze the requested query.",
    });
  } catch (err: any) {
    console.error("Error in AI Chat endpoint:", err);
    return res.status(500).json({
      error: err.message || "AI Chat failed. Please check network or API setup.",
    });
  }
});

// Vite Middleware & Static Production Handler
async function startServer() {
  try {
    if (process.env.NODE_ENV !== "production") {
      const hmrDisabled = process.env.DISABLE_HMR === "true";
      const vite = await createViteServer({
        server: {
          middlewareMode: true,
          hmr: hmrDisabled ? false : undefined,
        },
        appType: "spa",
      });
      app.use(vite.middlewares);
    } else {
      const distPath = path.join(process.cwd(), "dist");
      app.use(express.static(distPath));
      app.get("*", (req, res) => {
        res.sendFile(path.join(distPath, "index.html"));
      });
    }

    app.listen(PORT, "0.0.0.0", () => {
      console.log(`Server running on http://localhost:${PORT}`);
      console.log(`Server listening on 0.0.0.0:${PORT}`);
    });
  } catch (error) {
    console.error("Failed to start server:", error);
    process.exit(1);
  }
}

startServer();
